# Generated by Django 3.1.4 on 2021-02-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0014_auto_20210116_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitante',
            options={'ordering': ['fecha']},
        ),
        migrations.AlterField(
            model_name='instituciones',
            name='Tel_autorizador',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='cedula',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='celular',
            field=models.IntegerField(max_length=10),
        ),
    ]
