# Generated by Django 3.1.4 on 2021-02-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0015_auto_20210211_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituciones',
            name='Tel_autorizador',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='cedula',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='celular',
            field=models.CharField(max_length=10),
        ),
    ]
