# Generated by Django 3.1.4 on 2021-02-14 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0016_auto_20210211_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50)),
                ('posicion', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=10)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitante.visitante')),
            ],
        ),
    ]
