# Generated by Django 3.1.4 on 2021-02-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0017_acompanante'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='firma',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
