# Generated by Django 3.1.4 on 2021-02-14 20:34

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0018_visitante_firma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='firma',
        ),
        migrations.AddField(
            model_name='visitante',
            name='firma_entrada',
            field=jsignature.fields.JSignatureField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='firma_salida',
            field=jsignature.fields.JSignatureField(blank=True, null=True),
        ),
    ]
