# Generated by Django 3.1.4 on 2021-02-19 16:28

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0020_auto_20210219_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanante',
            name='firma_entrada',
            field=jsignature.fields.JSignatureField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acompanante',
            name='firma_salida',
            field=jsignature.fields.JSignatureField(blank=True, null=True),
        ),
    ]
