# Generated by Django 3.1.4 on 2021-02-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0021_auto_20210219_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanante',
            name='cedula',
            field=models.CharField(max_length=11),
        ),
    ]
